### ISSUE TITLE
certs

### ISSUE THREAD

**Issue by nazaros** [salrashid123/gcp_cicp_saml#1]
can you please update the project with the new certificates and check the filepath's in descriptions

**Comment by salrashid123** [comment]
sure, i can do that but is there an issue with the existing certs?
(if so, i'll just regen them from a sample CA see [instructions with openssl](https://github.com/salrashid123/grpc_web_with_gke#openssl)

as for the filepaths, did i miss volume path mount directory somewhere? (if so, can you point that out)

**Comment by nazaros** [comment]
thanks
not sure about the paths:
Certificate: copy 'sp_saml_cicp/server.crt' <- conents in 
python main./py <-  python main.py

**Comment by salrashid123** [comment]
i updated the typos in the README.md.  If you find anything else, pls feel free to submit a PR directly.

Also, i realized the openssl commands to create a cert were at the bottom of the readme
